version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          command: |
            docker login -u $DOCKER_USER -password-stdin $DOCKER_PASS
            cd odc-jupyter-image/
            docker build -t crcsi/odc-juypter-image:$CIRCLE_SHA1 -t crcsi/odc-juypter-image:latest .
            docker push crcsi/odc-juypter-image:$CIRCLE_SHA1 
            docker push crcsi/odc-juypter-image:latest
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
